apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: demo-0711-03 
  janus-idp.io/tekton: demo-0711-03
  backstage.io/kubernetes-id: demo-0711-03
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: demo-0711-03
resources: 
- application-dev.yaml