apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: demo-0711-03-gitops
  description: This is GitOps manifest for demo-0711-03   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: demo-0711-03
    janus-idp.io/tekton: demo-0711-03 
    backstage.io/kubernetes-id: demo-0711-03 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:demo-0711-03
